# Generated by Django 3.1.13 on 2021-08-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20210807_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='img_url',
            field=models.ImageField(blank=True, default='https://simpleisbetterthancomplex.com/tips/2016/07/25/django-tip-8-blank-or-null.html', upload_to='pokemon_images', verbose_name='Путь к картинке'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(blank=True, default='default', max_length=200, verbose_name='Английское название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(blank=True, default='default', max_length=200, verbose_name='Японское название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_ru',
            field=models.CharField(blank=True, default='none', max_length=200, verbose_name='Русское название'),
            preserve_default=False,
        ),
    ]
